### PR TITLE
Ben server side loop

### PR DESCRIPTION
**Pull request by cakey**
Starting to get there. Review welcome.

Things left:
- [x] Compute AIs server side.
- [x] Refactor Server globals into GOD handler.
- [ ] Decouple Game/Client handler (methods like broadcast)
- [x] Fix badly set destP
- [ ] Refactor ClientHandler and ServerHandler together (primarily how AI moves are passed around)
- [ ] Batch actions per tick
- [ ] Batch networking messages
- [ ] Use tick number when syncing. (Might punt) (We can rollback in time, update the state and then rerun subsequent tick actions, to reduce data staleness - super basic lag compensation)

@Stewart-Taylor @lee-woodridge @davidpribil

### CODE REVIEW

**Comment by cakey** [comment]
Getting some weird vibration effect with multiplayer before players have moved. Mismatch between destP and synced game state location perhaps.

**Comment by cakey** [comment]
@lee-woodridge Review?


I want to turn all actions into data. At each tick, each engine the takes a list of actions, and produces a list of messages to broadcast. This is how to decouple GameHandler and ClientHandler, and cleans up a ton of logic. Also gives batching.Also helps with lag compensation as we know which tick each action/message is associated with.

I'm punting on that for now, would rather get a bit more of the game going...

**Comment by Stewart-Taylor** [comment]
Reviewed it last night. Looks good ship it! :postbox:

**Comment by cakey** [comment]
Thanks buddy.

**Pull request merged**
