### PR TITLE
WIP : Ben server loop

### PR DESCRIPTION
**Pull request by cakey**
@lee-woodridge

### CODE REVIEW

**Comment by lee-woodridge** [comment]
@cakey merging although the camera thing should go away when we switch over to easel :+1:

**Comment by cakey** [comment]
dude what!?!?!?

**Comment by cakey** [comment]
why did you merge, this was WIP!

**Comment by cakey** [comment]
i meant merge those commits into your branch

**Comment by lee-woodridge** [comment]
Heh, try wording "might be worth you merging in this commit" better next time ;)

**Comment by lee-woodridge** [comment]
Revert it if you want?

**Comment by cakey** [comment]
nah its fine

**Pull request merged**
